/**
 * WCAG 2.1 Contrast Ratio Calculator and Dark Mode Generator
 */

// Convert hex (#RRGGBB or #RGB) to [r, g, b] (0-255)
export function hexToRgb(hex: string): [number, number, number] {
    let clean = hex.replace(/^#/, '');
    if (clean.length === 3) {
        clean = clean
            .split('')
            .map((c) => c + c)
            .join('');
    }
    const num = parseInt(clean, 16);
    return [(num >> 16) & 255, (num >> 8) & 255, num & 255];
}

// Convert [r, g, b] (0-255) to hex #RRGGBB
export function rgbToHex(r: number, g: number, b: number): string {
    const toHex = (c: number) => {
        const clamped = Math.max(0, Math.min(255, Math.round(c)));
        return clamped.toString(16).padStart(2, '0');
    };
    return `#${toHex(r)}${toHex(g)}${toHex(b)}`;
}

// Calculate relative luminance of an sRGB color per WCAG 2.1
export function getLuminance(hex: string): number {
    const [r, g, b] = hexToRgb(hex).map((c) => {
        const s = c / 255;
        return s <= 0.03928 ? s / 12.92 : Math.pow((s + 0.055) / 1.055, 2.4);
    });
    return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

// Calculate contrast ratio between two hex colors (1:1 to 21:1)
export function getContrastRatio(
    foregroundHex: string,
    backgroundHex: string,
): number {
    const l1 = getLuminance(foregroundHex);
    const l2 = getLuminance(backgroundHex);
    const lighter = Math.max(l1, l2);
    const darker = Math.min(l1, l2);
    const ratio = (lighter + 0.05) / (darker + 0.05);
    return Math.round(ratio * 100) / 100;
}

export interface ContrastAudit {
    ratio: number;
    passesNormalAA: boolean; // >= 4.5:1
    passesLargeAA: boolean; // >= 3.0:1
    passesAAA: boolean; // >= 7.0:1
    rating: 'AAA' | 'AA' | 'AA-Large' | 'Fail';
}

export function auditContrast(
    foregroundHex: string,
    backgroundHex: string,
): ContrastAudit {
    const ratio = getContrastRatio(foregroundHex, backgroundHex);
    const passesNormalAA = ratio >= 4.5;
    const passesLargeAA = ratio >= 3.0;
    const passesAAA = ratio >= 7.0;

    let rating: ContrastAudit['rating'] = 'Fail';
    if (passesAAA) {
        rating = 'AAA';
    } else if (passesNormalAA) {
        rating = 'AA';
    } else if (passesLargeAA) {
        rating = 'AA-Large';
    }

    return {
        ratio,
        passesNormalAA,
        passesLargeAA,
        passesAAA,
        rating,
    };
}

// Auto-generate high-contrast dark theme tokens from light theme tokens
export function autoGenerateDarkTokens(
    lightTokens: Record<string, string>,
): Record<string, string> {
    const darkTokens: Record<string, string> = { ...lightTokens };

    // Standard dark surfaces
    darkTokens.bg = '#121212';
    darkTokens.surface = '#1E1E1E';
    darkTokens.border = '#2E2E2E';
    darkTokens.text = '#F3F4F6';
    darkTokens.text_muted = '#9CA3AF';

    // Lift and adjust brand / status colors for dark background vibrancy and contrast
    const brighten = (hex: string, factor = 1.3) => {
        const [r, g, b] = hexToRgb(hex);
        return rgbToHex(r * factor, g * factor, b * factor);
    };

    if (lightTokens.primary)
        darkTokens.primary = brighten(lightTokens.primary, 1.25);
    if (lightTokens.secondary)
        darkTokens.secondary = brighten(lightTokens.secondary, 1.4);
    if (lightTokens.accent)
        darkTokens.accent = brighten(lightTokens.accent, 1.2);

    if (lightTokens.status_received) darkTokens.status_received = '#60A5FA';
    if (lightTokens.status_verification)
        darkTokens.status_verification = '#A78BFA';
    if (lightTokens.status_categorised)
        darkTokens.status_categorised = '#818CF8';
    if (lightTokens.status_assigned) darkTokens.status_assigned = '#F472B6';
    if (lightTokens.status_assistance) darkTokens.status_assistance = '#FBBF24';
    if (lightTokens.status_followup) darkTokens.status_followup = '#34D399';
    if (lightTokens.status_resolved) darkTokens.status_resolved = '#34D399';
    if (lightTokens.status_rejected) darkTokens.status_rejected = '#F87171';
    if (lightTokens.status_onhold) darkTokens.status_onhold = '#9CA3AF';

    return darkTokens;
}
