import React, { useState, useMemo } from 'react';
import { useForm, router } from '@inertiajs/react';
import {
    Eye,
    History,
    Moon,
    Palette,
    RotateCcw,
    Sparkles,
    Sun,
    Tag,
    UploadCloud,
} from 'lucide-react';
import AdminLayout from '../../../components/AdminLayout';
import { auditContrast, autoGenerateDarkTokens } from '../../../lib/contrast';
import { useTranslation } from '../../../lib/i18n';

interface ThemeVersionData {
    id: number;
    version: number;
    light: Record<string, string>;
    dark: Record<string, string>;
    meta?: Record<string, unknown>;
    is_published: boolean;
    published_at?: string;
    notes?: string;
    publisher?: { id: number; name: string };
}

interface ThemeIndexProps {
    current: ThemeVersionData | null;
    history: ThemeVersionData[];
}

const defaultLight: Record<string, string> = {
    primary: '#006026',
    secondary: '#79573c',
    accent: '#1b7a38',
    bg: '#fff8f5',
    surface: '#fff8f5',
    text: '#2a170b',
    text_muted: '#3f493f',
    border: '#bfcabb',
    status_received: '#2563EB',
    status_verification: '#7C3AED',
    status_categorised: '#4F46E5',
    status_assigned: '#1b7a38',
    status_assistance: '#D97706',
    status_followup: '#059669',
    status_resolved: '#006026',
    status_rejected: '#ba1a1a',
    status_onhold: '#6f7a6e',
};

const defaultDark: Record<string, string> = {
    primary: '#7fda8c',
    secondary: '#eabe9c',
    accent: '#9bf7a6',
    bg: '#1a110c',
    surface: '#25180f',
    text: '#ffede5',
    text_muted: '#bfcabb',
    border: '#412c1f',
    status_received: '#60A5FA',
    status_verification: '#A78BFA',
    status_categorised: '#818CF8',
    status_assigned: '#7fda8c',
    status_assistance: '#FBBF24',
    status_followup: '#34D399',
    status_resolved: '#7fda8c',
    status_rejected: '#F87171',
    status_onhold: '#9CA3AF',
};

interface ThemeFormData {
    light: Record<string, string>;
    dark: Record<string, string>;
    notes: string;
    meta: Record<string, any>;
}

export default function ThemeIndex({ current, history }: ThemeIndexProps) {
    const { t } = useTranslation();
    const [modeTab, setModeTab] = useState<'light' | 'dark'>('light');

    const { data, setData, post, processing } = useForm<ThemeFormData>({
        light: current?.light || defaultLight,
        dark: current?.dark || defaultDark,
        notes: '',
        meta: (current?.meta as Record<string, unknown>) || {},
    });

    const activePalette = modeTab === 'light' ? data.light : data.dark;

    const handleColorChange = (key: string, value: string) => {
        if (modeTab === 'light') {
            setData('light', { ...data.light, [key]: value });
        } else {
            setData('dark', { ...data.dark, [key]: value });
        }
    };

    // Auto generate dark mode from light mode
    const handleAutoGenerateDark = () => {
        const generated = autoGenerateDarkTokens(data.light);
        setData('dark', generated);
        setModeTab('dark');
    };

    // Real-time WCAG Contrast Audits
    const contrastAudit = useMemo(() => {
        const textOnSurface = auditContrast(
            activePalette.text || '#1F2937',
            activePalette.surface || '#FFFFFF',
        );
        const textMutedOnSurface = auditContrast(
            activePalette.text_muted || '#6B7280',
            activePalette.surface || '#FFFFFF',
        );
        const primaryOnBg = auditContrast(
            activePalette.primary || '#B33925',
            activePalette.bg || '#FDFBF7',
        );

        return { textOnSurface, textMutedOnSurface, primaryOnBg };
    }, [activePalette]);

    const handlePublish = (e: React.FormEvent) => {
        e.preventDefault();
        post('/admin/theme/publish');
    };

    const handleRollback = (id: number) => {
        if (
            confirm('Are you sure you want to rollback to this theme version?')
        ) {
            router.post(`/admin/theme/rollback/${id}`);
        }
    };

    return (
        <AdminLayout title={t('theme.editor.title', 'Theme & Appearance')}>
            <div className="space-y-8">
                {/* Header */}
                <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
                    <div>
                        <h2 className="text-thh-text flex items-center gap-2.5 text-2xl font-bold tracking-tight">
                            <Palette className="text-thh-primary h-6 w-6" />
                            <span>
                                {t(
                                    'theme.editor.title',
                                    'Theme & Appearance Manager',
                                )}
                            </span>
                        </h2>
                        <p className="text-thh-text-muted mt-1 text-sm">
                            {t(
                                'theme.editor.subtitle',
                                'Live control over platform colors, WCAG contrast compliance and brand identity',
                            )}
                        </p>
                    </div>

                    <div className="flex items-center gap-3">
                        <span className="bg-thh-primary/10 text-thh-primary border-thh-primary/20 inline-flex items-center gap-1.5 rounded-full border px-3 py-1 text-xs font-semibold">
                            <Tag className="h-3.5 w-3.5" />
                            <span>Active Version #{current?.version || 1}</span>
                        </span>

                        <button
                            type="button"
                            onClick={handleAutoGenerateDark}
                            className="border-thh-border bg-thh-surface text-thh-text hover:bg-thh-bg inline-flex items-center gap-2 rounded-lg border px-3.5 py-2 text-xs font-medium shadow-2xs transition-colors"
                        >
                            <Sparkles className="text-thh-accent h-3.5 w-3.5" />
                            <span>
                                {t(
                                    'theme.editor.auto_dark_button',
                                    'Auto-Generate Dark Mode',
                                )}
                            </span>
                        </button>
                    </div>
                </div>

                {/* Main Editor Grid */}
                <div className="grid grid-cols-1 gap-8 lg:grid-cols-12">
                    {/* Left Panel: Token Controls (7 Cols) */}
                    <div className="space-y-6 lg:col-span-7">
                        {/* Mode Selector Tab */}
                        <div className="bg-thh-surface border-thh-border flex items-center rounded-xl border p-1">
                            <button
                                type="button"
                                onClick={() => setModeTab('light')}
                                className={`flex flex-1 items-center justify-center gap-2 rounded-lg py-2 text-xs font-semibold transition-all ${
                                    modeTab === 'light'
                                        ? 'bg-thh-primary text-white shadow-xs'
                                        : 'text-thh-text-muted hover:text-thh-text'
                                }`}
                            >
                                <Sun className="h-4 w-4" />
                                <span>
                                    {t(
                                        'theme.editor.light_tab',
                                        'Light Mode Tokens',
                                    )}
                                </span>
                            </button>

                            <button
                                type="button"
                                onClick={() => setModeTab('dark')}
                                className={`flex flex-1 items-center justify-center gap-2 rounded-lg py-2 text-xs font-semibold transition-all ${
                                    modeTab === 'dark'
                                        ? 'bg-thh-primary text-white shadow-xs'
                                        : 'text-thh-text-muted hover:text-thh-text'
                                }`}
                            >
                                <Moon className="h-4 w-4" />
                                <span>
                                    {t(
                                        'theme.editor.dark_tab',
                                        'Dark Mode Tokens',
                                    )}
                                </span>
                            </button>
                        </div>

                        {/* WCAG Contrast Score Banner */}
                        <div className="bg-thh-surface border-thh-border rounded-xl border p-4.5 shadow-2xs">
                            <div className="mb-3 flex items-center justify-between">
                                <h3 className="text-thh-text flex items-center gap-1.5 text-xs font-bold tracking-wider uppercase">
                                    <span>
                                        {t(
                                            'theme.editor.contrast_check_title',
                                            'WCAG 2.1 Contrast Compliance',
                                        )}
                                    </span>
                                </h3>
                                <span
                                    className={`rounded-full px-2.5 py-0.5 text-xs font-bold uppercase ${
                                        contrastAudit.textOnSurface
                                            .passesNormalAA
                                            ? 'border border-emerald-500/20 bg-emerald-500/10 text-emerald-600'
                                            : 'border border-rose-500/20 bg-rose-500/10 text-rose-600'
                                    }`}
                                >
                                    {contrastAudit.textOnSurface.rating} (
                                    {contrastAudit.textOnSurface.ratio}:1)
                                </span>
                            </div>

                            <div className="grid grid-cols-3 gap-3 text-xs">
                                <div className="bg-thh-bg border-thh-border rounded-lg border p-2.5">
                                    <span className="text-thh-text-muted block text-[11px]">
                                        Body on Surface
                                    </span>
                                    <span className="text-thh-text mt-0.5 block font-bold">
                                        {contrastAudit.textOnSurface.ratio}:1
                                    </span>
                                    <span className="text-[10px] font-semibold text-emerald-600">
                                        Passes AA (≥4.5)
                                    </span>
                                </div>
                                <div className="bg-thh-bg border-thh-border rounded-lg border p-2.5">
                                    <span className="text-thh-text-muted block text-[11px]">
                                        Muted on Surface
                                    </span>
                                    <span className="text-thh-text mt-0.5 block font-bold">
                                        {contrastAudit.textMutedOnSurface.ratio}
                                        :1
                                    </span>
                                    <span className="text-[10px] font-semibold text-emerald-600">
                                        {contrastAudit.textMutedOnSurface
                                            .passesNormalAA
                                            ? 'Passes AA'
                                            : 'Large Text'}
                                    </span>
                                </div>
                                <div className="bg-thh-bg border-thh-border rounded-lg border p-2.5">
                                    <span className="text-thh-text-muted block text-[11px]">
                                        Primary on Canvas
                                    </span>
                                    <span className="text-thh-text mt-0.5 block font-bold">
                                        {contrastAudit.primaryOnBg.ratio}:1
                                    </span>
                                    <span className="text-[10px] font-semibold text-emerald-600">
                                        Brand Contrast
                                    </span>
                                </div>
                            </div>
                        </div>

                        {/* Color Groups Form */}
                        <form onSubmit={handlePublish} className="space-y-6">
                            {/* Brand Palette */}
                            <div className="bg-thh-surface border-thh-border space-y-4 rounded-xl border p-5 shadow-2xs">
                                <h3 className="text-thh-text text-xs font-bold tracking-wider uppercase">
                                    Brand & Core Colors
                                </h3>
                                <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
                                    {[
                                        {
                                            key: 'primary',
                                            label: 'Primary (Terracotta)',
                                        },
                                        {
                                            key: 'secondary',
                                            label: 'Secondary (Forest)',
                                        },
                                        {
                                            key: 'accent',
                                            label: 'Accent (Ochre Gold)',
                                        },
                                    ].map(({ key, label }) => (
                                        <div key={key} className="space-y-1.5">
                                            <label className="text-thh-text block text-xs font-medium">
                                                {label}
                                            </label>
                                            <div className="flex items-center gap-2">
                                                <input
                                                    type="color"
                                                    value={
                                                        activePalette[key] ||
                                                        '#000000'
                                                    }
                                                    onChange={(e) =>
                                                        handleColorChange(
                                                            key,
                                                            e.target.value,
                                                        )
                                                    }
                                                    className="border-thh-border h-9 w-9 cursor-pointer rounded-lg border bg-transparent p-0.5"
                                                />
                                                <input
                                                    type="text"
                                                    value={
                                                        activePalette[key] || ''
                                                    }
                                                    onChange={(e) =>
                                                        handleColorChange(
                                                            key,
                                                            e.target.value,
                                                        )
                                                    }
                                                    className="border-thh-border bg-thh-bg text-thh-text focus:ring-thh-primary flex-1 rounded-lg border px-3 py-1.5 font-mono text-xs focus:ring-1 focus:outline-hidden"
                                                />
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>

                            {/* Canvas & Typography Colors */}
                            <div className="bg-thh-surface border-thh-border space-y-4 rounded-xl border p-5 shadow-2xs">
                                <h3 className="text-thh-text text-xs font-bold tracking-wider uppercase">
                                    Surface & Typography
                                </h3>
                                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                                    {[
                                        {
                                            key: 'bg',
                                            label: 'Canvas Background',
                                        },
                                        {
                                            key: 'surface',
                                            label: 'Card / Surface',
                                        },
                                        { key: 'text', label: 'Body Text' },
                                        {
                                            key: 'text_muted',
                                            label: 'Muted Text',
                                        },
                                        {
                                            key: 'border',
                                            label: 'Border / Divider',
                                        },
                                    ].map(({ key, label }) => (
                                        <div key={key} className="space-y-1.5">
                                            <label className="text-thh-text block text-xs font-medium">
                                                {label}
                                            </label>
                                            <div className="flex items-center gap-2">
                                                <input
                                                    type="color"
                                                    value={
                                                        activePalette[key] ||
                                                        '#000000'
                                                    }
                                                    onChange={(e) =>
                                                        handleColorChange(
                                                            key,
                                                            e.target.value,
                                                        )
                                                    }
                                                    className="border-thh-border h-9 w-9 cursor-pointer rounded-lg border bg-transparent p-0.5"
                                                />
                                                <input
                                                    type="text"
                                                    value={
                                                        activePalette[key] || ''
                                                    }
                                                    onChange={(e) =>
                                                        handleColorChange(
                                                            key,
                                                            e.target.value,
                                                        )
                                                    }
                                                    className="border-thh-border bg-thh-bg text-thh-text focus:ring-thh-primary flex-1 rounded-lg border px-3 py-1.5 font-mono text-xs focus:ring-1 focus:outline-hidden"
                                                />
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>

                            {/* Case Status Lifecycle Colors */}
                            <div className="bg-thh-surface border-thh-border space-y-4 rounded-xl border p-5 shadow-2xs">
                                <h3 className="text-thh-text text-xs font-bold tracking-wider uppercase">
                                    Case Lifecycle State Tokens
                                </h3>
                                <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
                                    {[
                                        {
                                            key: 'status_received',
                                            label: 'Received',
                                        },
                                        {
                                            key: 'status_verification',
                                            label: 'Verification',
                                        },
                                        {
                                            key: 'status_categorised',
                                            label: 'Categorised',
                                        },
                                        {
                                            key: 'status_assigned',
                                            label: 'Assigned',
                                        },
                                        {
                                            key: 'status_assistance',
                                            label: 'Assistance',
                                        },
                                        {
                                            key: 'status_followup',
                                            label: 'Follow-up',
                                        },
                                        {
                                            key: 'status_resolved',
                                            label: 'Resolved',
                                        },
                                        {
                                            key: 'status_rejected',
                                            label: 'Rejected',
                                        },
                                        {
                                            key: 'status_onhold',
                                            label: 'On Hold',
                                        },
                                    ].map(({ key, label }) => (
                                        <div key={key} className="space-y-1.5">
                                            <label className="text-thh-text block text-xs font-medium">
                                                {label}
                                            </label>
                                            <div className="flex items-center gap-2">
                                                <input
                                                    type="color"
                                                    value={
                                                        activePalette[key] ||
                                                        '#000000'
                                                    }
                                                    onChange={(e) =>
                                                        handleColorChange(
                                                            key,
                                                            e.target.value,
                                                        )
                                                    }
                                                    className="border-thh-border h-8 w-8 cursor-pointer rounded-lg border bg-transparent p-0.5"
                                                />
                                                <input
                                                    type="text"
                                                    value={
                                                        activePalette[key] || ''
                                                    }
                                                    onChange={(e) =>
                                                        handleColorChange(
                                                            key,
                                                            e.target.value,
                                                        )
                                                    }
                                                    className="border-thh-border bg-thh-bg text-thh-text focus:ring-thh-primary flex-1 rounded-lg border px-2.5 py-1 font-mono text-xs focus:ring-1 focus:outline-hidden"
                                                />
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>

                            {/* Publish Notes and Actions */}
                            <div className="bg-thh-surface border-thh-border space-y-4 rounded-xl border p-5 shadow-2xs">
                                <label className="text-thh-text block text-xs font-bold tracking-wider uppercase">
                                    Publish Notes (Optional)
                                </label>
                                <input
                                    type="text"
                                    placeholder="e.g. Adjusted secondary green contrast for WCAG AAA"
                                    value={data.notes}
                                    onChange={(e) =>
                                        setData('notes', e.target.value)
                                    }
                                    className="border-thh-border bg-thh-bg text-thh-text focus:ring-thh-primary w-full rounded-lg border px-3.5 py-2 text-sm focus:ring-1 focus:outline-hidden"
                                />

                                <div className="flex items-center justify-end gap-3 pt-2">
                                    <button
                                        type="submit"
                                        disabled={processing}
                                        className="bg-thh-primary inline-flex items-center gap-2 rounded-lg px-5 py-2.5 text-sm font-semibold text-white shadow-xs transition-all hover:opacity-95 disabled:opacity-50"
                                    >
                                        <UploadCloud className="h-4 w-4" />
                                        <span>
                                            {processing
                                                ? 'Publishing...'
                                                : t(
                                                      'theme.editor.publish_button',
                                                      'Publish Live Theme',
                                                  )}
                                        </span>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>

                    {/* Right Panel: Live Dynamic Preview & Version History (5 Cols) */}
                    <div className="space-y-6 lg:col-span-5">
                        {/* Live Component Preview Card */}
                        <div
                            className="space-y-6 rounded-2xl border p-6 shadow-sm transition-all"
                            style={{
                                backgroundColor: activePalette.bg || '#FDFBF7',
                                borderColor: activePalette.border || '#E5E7EB',
                                color: activePalette.text || '#1F2937',
                            }}
                        >
                            <div
                                className="flex items-center justify-between border-b pb-3"
                                style={{ borderColor: activePalette.border }}
                            >
                                <div className="flex items-center gap-2">
                                    <Eye
                                        className="h-4 w-4"
                                        style={{ color: activePalette.primary }}
                                    />
                                    <span
                                        className="text-xs font-bold tracking-wider uppercase"
                                        style={{ color: activePalette.text }}
                                    >
                                        {t(
                                            'theme.editor.preview_heading',
                                            'Live UI Preview',
                                        )}
                                    </span>
                                </div>
                                <span
                                    className="rounded-full px-2 py-0.5 text-[11px] font-semibold"
                                    style={{
                                        backgroundColor:
                                            (activePalette.primary ||
                                                '#B33925') + '15',
                                        color:
                                            activePalette.primary || '#B33925',
                                    }}
                                >
                                    {modeTab.toUpperCase()} PREVIEW
                                </span>
                            </div>

                            {/* Sample Case Status Card */}
                            <div
                                className="space-y-3 rounded-xl border p-4 shadow-xs"
                                style={{
                                    backgroundColor:
                                        activePalette.surface || '#FFFFFF',
                                    borderColor:
                                        activePalette.border || '#E5E7EB',
                                }}
                            >
                                <div className="flex items-center justify-between">
                                    <span
                                        className="font-mono text-xs font-bold"
                                        style={{ color: activePalette.text }}
                                    >
                                        THH-2026-00042
                                    </span>
                                    <span
                                        className="rounded-full px-2.5 py-0.5 text-[11px] font-bold"
                                        style={{
                                            backgroundColor:
                                                (activePalette.status_resolved ||
                                                    '#10B981') + '20',
                                            color:
                                                activePalette.status_resolved ||
                                                '#10B981',
                                        }}
                                    >
                                        ● Resolved
                                    </span>
                                </div>

                                <div>
                                    <h4
                                        className="text-sm leading-snug font-bold"
                                        style={{ color: activePalette.text }}
                                    >
                                        Solar Water Pump Installation
                                    </h4>
                                    <p
                                        className="mt-1 text-xs"
                                        style={{
                                            color: activePalette.text_muted,
                                        }}
                                    >
                                        Narmada District • Dediapada Taluka •
                                        Chikda Village
                                    </p>
                                </div>

                                <div className="flex items-center gap-2 pt-2">
                                    <button
                                        type="button"
                                        className="rounded-lg px-3 py-1.5 text-xs font-semibold text-white shadow-xs"
                                        style={{
                                            backgroundColor:
                                                activePalette.primary,
                                        }}
                                    >
                                        Take Action
                                    </button>
                                    <button
                                        type="button"
                                        className="rounded-lg border px-3 py-1.5 text-xs font-semibold"
                                        style={{
                                            borderColor: activePalette.border,
                                            color: activePalette.secondary,
                                            backgroundColor:
                                                activePalette.surface,
                                        }}
                                    >
                                        View Timeline
                                    </button>
                                </div>
                            </div>

                            {/* Status Indicators Palette Preview */}
                            <div
                                className="space-y-2.5 rounded-xl border p-4 shadow-xs"
                                style={{
                                    backgroundColor:
                                        activePalette.surface || '#FFFFFF',
                                    borderColor:
                                        activePalette.border || '#E5E7EB',
                                }}
                            >
                                <span
                                    className="block text-xs font-bold"
                                    style={{ color: activePalette.text }}
                                >
                                    Case Lifecycle Badges
                                </span>
                                <div className="flex flex-wrap gap-1.5">
                                    {[
                                        {
                                            label: 'Received',
                                            color: activePalette.status_received,
                                        },
                                        {
                                            label: 'Verification',
                                            color: activePalette.status_verification,
                                        },
                                        {
                                            label: 'Categorised',
                                            color: activePalette.status_categorised,
                                        },
                                        {
                                            label: 'Assigned',
                                            color: activePalette.status_assigned,
                                        },
                                        {
                                            label: 'Assistance',
                                            color: activePalette.status_assistance,
                                        },
                                        {
                                            label: 'Resolved',
                                            color: activePalette.status_resolved,
                                        },
                                        {
                                            label: 'Rejected',
                                            color: activePalette.status_rejected,
                                        },
                                    ].map((s) => (
                                        <span
                                            key={s.label}
                                            className="rounded-md px-2 py-0.5 text-[10px] font-semibold"
                                            style={{
                                                backgroundColor:
                                                    (s.color || '#888888') +
                                                    '15',
                                                color: s.color || '#888888',
                                                border: `1px solid ${s.color || '#888888'}30`,
                                            }}
                                        >
                                            {s.label}
                                        </span>
                                    ))}
                                </div>
                            </div>
                        </div>

                        {/* Version History & Rollback */}
                        <div className="bg-thh-surface border-thh-border space-y-4 rounded-xl border p-5 shadow-2xs">
                            <h3 className="text-thh-text flex items-center gap-2 text-xs font-bold tracking-wider uppercase">
                                <History className="text-thh-text-muted h-4 w-4" />
                                <span>
                                    {t(
                                        'theme.editor.history_heading',
                                        'Theme Version History',
                                    )}
                                </span>
                            </h3>

                            <div className="divide-thh-border divide-y">
                                {history.map((ver) => (
                                    <div
                                        key={ver.id}
                                        className="flex items-center justify-between py-3 text-xs"
                                    >
                                        <div>
                                            <div className="flex items-center gap-2">
                                                <span className="text-thh-text font-bold">
                                                    Version #{ver.version}
                                                </span>
                                                {ver.is_published && (
                                                    <span className="rounded-md bg-emerald-500/10 px-1.5 py-0.5 text-[10px] font-bold text-emerald-600">
                                                        Active
                                                    </span>
                                                )}
                                            </div>
                                            <p className="text-thh-text-muted mt-0.5 text-[11px]">
                                                {ver.notes ||
                                                    'Routine theme update'}
                                            </p>
                                        </div>

                                        <div>
                                            {!ver.is_published && (
                                                <button
                                                    type="button"
                                                    onClick={() =>
                                                        handleRollback(ver.id)
                                                    }
                                                    className="border-thh-border text-thh-text hover:bg-thh-bg inline-flex items-center gap-1 rounded-md border px-2.5 py-1 text-xs font-medium transition-colors"
                                                >
                                                    <RotateCcw className="text-thh-accent h-3 w-3" />
                                                    <span>Rollback</span>
                                                </button>
                                            )}
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </AdminLayout>
    );
}
